### ISSUE TITLE
How i use this?

### ISSUE THREAD

**Issue by koply** [SharpMC/SharpMC#13]
I think this repo is Minecraft server client on C# base. How i use this, please contact me. Discord: MusaBrt ▲#8150

**Comment by InDieTasten** [comment]
It's not a client. It's a MC server implemented in C#, just as it states in the readme here: https://github.com/SharpMC/SharpMC#what-is-sharpmc

**Comment by kennyvv** [comment]
Sorry for the late late response, but if you are looking for a client check out my other project.
https://github.com/kennyvv/Alex
